language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: kaushik.patel@sas.com
  api: https://api.run.pivotal.io
  organization: CF Class
  space: staging
  password:
    secure: qJ0FKMl9Lyz9hX47rtIx9ra0PhEgPudaAubJSanMQZr43nwkazBGoEACeZae+ySp6aWqnRX+OLsx+Y5w8Rvx3r1UKO1Bjg6A+lFemuFFzwlDwJHveTzaw1+nw16b3nui479i0qmA21T/lKZ0tI+XFSnrWrMzcH3K2aQ0jLVZaD1FXBU+4wIlZ4gNWqhr5oMQxp5Oq/SkN1OnAe/k6sUFJ9rOuW65IpzEsKEerI6ZeyflTwRyYb93UP5duB4RXlnEJRkDXN9ofyU9oEH02PVwBH6ksqyACXlQgRjcDAH7HrJG2auJ+3WkqAzkRhnEmeVlqhlmuEQ364118x9Zn8ErUo43seM0dsQ/K5YKdSkigmi4vF38OeNiE65UWtsH/AwrmHrP8W5im88k93OHRKtgHinlIDtjEOBa+hDy4i9UYkAaIvM3X/NFGNUjjKWMfho0s3YsKFWKPCeGGHlZBJJeL4ivOlUsO6bDpi17SScE+d2rbtc5H9hrIW8ZGLf+8mV5iVhildKGJJtJ5J3g/QorAq7h8h82kH6emMQ4HX56DLXYy7Y944jlVQpkgDnF7zo0b+nGGNuX3kIi1VKzhFWRg8lrmdL7sbaXCvhLCVXFa2/07ZMsG1FD0L2SwpZ6m1pUXUDl7IlzjyVfdq+0pDIQoJp3od5ZvwR2je8fuKg6NHs=
