language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: kaushik.patel@sas.com
  api: https://api.run.pivotal.io
  organization: "CF Class"
  space: staging
  password: CF4$Class
