language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: kaushik.patel@sas.com
  api: https://api.run.pivotal.io
  organization: CF Class
  space: staging
  password:
    secure: UAmngpMVih6t5j4+9EoGNrlDUM/pabChf3oALfqDVbZtJNWz0r9TknXrBo3MBIFwOKevpHvaMz7vNY2peVt39fh6/5b5shnYMMNhT0vh2V9CF7X7vPnBoL30dWINQLbXTdHvcqde+PW+3Yjzbbt4VhTKCMLY1dsnMJD5Kg8JKixXirAp86vYI2Iiu0FEE81ZooZGXvIdr6miRqZpqvBxzxibFAeSaeKc2tQ0vdnfxnVDdRpABMvuclT0zDyinJVaEdelGa7/R+lmtN6m54rC+ja5LAAYTvTMw441bGZUpZ6IQy1wY4PlNuBuvd3JklNQ4P7POM1jaC66Z+VYBbKHIzSx+R03gaviDcLCoUSp+omcE21F7l6nNzxA07issmNpRVAeWawVmXFRgcAKLdQVtYzNsgXeI2QL0CJcTvZzycJwB/oCd0PZLd8Ci+Tbsox8Pp7xNBcWxzrbE+xCMuxJjjr6IvtefG9ucsQSTuytkDkMSFLH6i+tuOClDMtbI35yz/DokZxeVGDn/NBWqTUojlKgu8utx5DV7WUNxp4M/9ox6RQ3h1Bo70QDEntdDG4S9/+HkKwQmo0Q2DzqBmfdIvZCfB1r/SlLt4sbkEfzumcldEyNxgb+InlrPytZZItFTbLH7pY63BS3PxbgKZEUxSsrjqSa3+3222+w6mE2J08=
