language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: kaushik.patel@sas.com
  api: https://api.run.pivotal.io
  organization: CF Class
  space: staging
  password:
    secure: TStppAZcPncBvYtGoI61BOoZEe+FTwhKGDQKKQ8B4m0g8o/nIwV5YKPPHAMaWoMq5kUj2QGPECJe5FqkYy8Siu2hXZyEc7RdlLJXX96Mz7Tfn74Cq9YzGuJSMvHS8DDJ6bSODsDkYYn37qJ5iNKOl4tWpeg6shior5wzGgbBNbka+NN8jfEGjaKJBufkTAyxE3/Q3arUkD7+z7aG974/BdVlx3c/v+rjoKj80CWQQrQgs6gG3JzgfWdi8t41sFdsjRiXYyoLaQipptzn7P315Q8I4PWFj4Ubx4O/9SPxT5mM2lYzOQmdtS3XXQwd3RVISeHwnEk7PFqG1ZxV/kdh4iUcQ+1cj51e7/f24a+GR/JUI+lWQhoOrg29C0Yp0jM0bqo+O/GjGL5OjRQMtr5Qqo2MGKkvY9i1Gy8mJva5DWXhs+A8tXnJYIgZpyBakqPr6phsSN2ba6YYRCrv3maSYg3Gw89qbrdx6AJcU2W/JoTNMXaPu6p6IKt8EQglLuBGIsjAbmx5XzkDFEvJuDWvTI5NOFYhkAJV18xQh2arKLGFfZXiAlk/qXL86NOVhPVu67Ui5IqeCBJ8n7FW5rGneVSNqQeKHwUzoc6hqmr8zn30hviLSF9ucBhevty5RWiLa/oysADJG0DCkfRFqXuzjiE5tzBP6JRVrDd8UvFV+Hk=
